
spring:
    datasource:
        url: jdbc:oracle:thin:@//localhost:27017/howdyl
        username: david
        password: tochange
        driver-class-name: mongodb.jdbc.MongoDriver
    jpa:
        # Crea les taules a la BD automàticament
        # Només ho activem quan volem fer canvis a la BD perquè fa 
        # que l'aplicació trigui molt en arrencar
        # generate-ddl: true    
        show-sql: true
        
hibernate:
    showSql: true
    dialect: org.hibernate.dialect.Oracle10gDialect
